pid_control_wrapper:
  planner: "teleop"

  enableBuoyancyComp: False
  enableVelocityFeedForward: False

  vel_src_xy: "controller"
  vel_src_z: "controller"
  vel_src_heading: "controller"
  vel_src_attitude: "controller"

  acc_src_xy: "planner"
  acc_src_z: "planner"
  acc_src_heading: "planner"
  acc_src_attitude: "controller"