name: Build Project

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step: Set up Docker Buildx (if needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step: Build the CI image
      - name: Build Docker image
        run: |
          chmod +x ./build/scripts/build-ci.sh
          ./build/scripts/build-ci.sh

      - name: Run build command inside Docker container
        run: |
          docker run -v ${{ github.workspace }}:/catkin_ws --rm /bin/bash -c "cd /catkin_ws && catkin_build"
