services:

  # Platform-specific layer
  orin-platform:
    image: tauv/orin-platform
    build:
      context: ./platform
      dockerfile: Dockerfile.orin


  # Common layer
  orin-common:
    image: tauv/orin-common
    build:
      context: ./common
      dockerfile: Dockerfile.common
      args:
        BASE_IMAGE: tauv/orin-platform
    depends_on:
      - orin-platform


  # Application layer
  tauv-kingfisher:
    build:
      context: ./apps/vehicle
      dockerfile: Dockerfile.kingfisher
      args:
        - BASE_IMAGE=tauv/orin-common
    image: tauv/vehicle-kingfisher
    volumes:
      - /dev:/dev
      - /tm.X11-unix/:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - /home/tartanauv/shared:/shared
      - /home/tartanauv/data:/data
    environment:
      XAUTHORITY: /tmp/.docker.xauth
    network_mode: "host"
    privileged: true
    runtime: nvidia
    depends_on:
      - orin-common
