#!/usr/bin/env python3
import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'src'))
from centernet.node import centernet_node

if __name__ == "__main__":
    centernet_node.main()
