name: Build Project

on:
  push:
    branches:
      - gleb/restructure
  pull_request:
    branches:
      - gleb/restructure

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step: Set up Docker Buildx (if needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step: Build the CI image
      - name: Build Docker image
        run: |
          chmod +x ${{ github.workspace }}/containers/scripts/build-ci.sh
          ${{ github.workspace }}/containers/scripts/build-ci.sh

      - name: Get Commit Hash
        id: vars
        run: echo "COMMIT_HASH=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      - name: Run build command inside Docker container
        run: |
          docker run \
            -v  ${{ github.workspace }}:/catkin_ws \
            tauv/x86-nvidia-ci:e1bd9d8 \
            /bin/bash -c "source /opt/ros/noetic/setup.bash && cd catkin_ws && catkin build"
